version: '3.1'

services:
  db:
    image: mongo:4.4.0
    ports:
      - "27017:27017"

  api:
    build: ./api
    command: npm run dev
    environment:
      NODE_ENV: "development"
      ME_CONFIG_MONGODB_SERVER: "db"
      ME_CONFIG_MONGODB_PORT: 27017
      FRONTEND_URL: "http://frontend:5000"
    volumes:
      - ./api:/code:delegated
      - /code/node_modules/
    depends_on:
      - db
    ports:
      - "8081:8081"

  frontend:
    build: ./frontend
    command: npm start #run dev
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
      TARGET_ENV: "development"
      API_URL: "http://api:5001"
    volumes:
      - ./frontend:/code:delegated
      - /code/node_modules/
    ports:
      - "5000:3000"
